# Generated by Django 5.0.6 on 2024-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=50)),
                ('categoriaEstrellas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=50)),
                ('nombreAerolinea', models.CharField(max_length=50)),
                ('estadiaNoches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAerolinea', models.CharField(max_length=50)),
            ],
        ),
    ]
